# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PC_IN_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HostGo(object):
    def setupUi(self, HostGo):
        HostGo.setObjectName("HostGo")
        HostGo.resize(700, 200)
        HostGo.setMinimumSize(QtCore.QSize(700, 200))
        HostGo.setMaximumSize(QtCore.QSize(700, 200))
        self.SharePhrase = QtWidgets.QLabel(HostGo)
        self.SharePhrase.setGeometry(QtCore.QRect(-2, 120, 701, 71))
        self.SharePhrase.setAlignment(QtCore.Qt.AlignCenter)
        self.SharePhrase.setObjectName("SharePhrase")
        self.horizontalLayoutWidget = QtWidgets.QWidget(HostGo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 701, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ShowPhrase = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ShowPhrase.setObjectName("ShowPhrase")
        self.horizontalLayout.addWidget(self.ShowPhrase)
        self.IPPhrase = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.IPPhrase.setText("")
        self.IPPhrase.setAlignment(QtCore.Qt.AlignCenter)
        self.IPPhrase.setReadOnly(False)
        self.IPPhrase.setObjectName("IPPhrase")
        self.horizontalLayout.addWidget(self.IPPhrase)
        self.OnPush = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.OnPush.setObjectName("OnPush")
        self.horizontalLayout.addWidget(self.OnPush)

        self.retranslateUi(HostGo)
        QtCore.QMetaObject.connectSlotsByName(HostGo)

    def retranslateUi(self, HostGo):
        _translate = QtCore.QCoreApplication.translate
        HostGo.setWindowTitle(_translate("HostGo", "IP Share"))
        self.SharePhrase.setText(_translate("HostGo", "Share it with your client user!"))
        self.ShowPhrase.setText(_translate("HostGo", "Your IP is:"))
        self.OnPush.setText(_translate("HostGo", "Turn on"))
