# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PR_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PictureReceiver(object):
    def setupUi(self, PictureReceiver):
        PictureReceiver.setObjectName("PictureReceiver")
        PictureReceiver.resize(1286, 769)
        self.centralwidget = QtWidgets.QWidget(PictureReceiver)
        self.centralwidget.setObjectName("centralwidget")
        self.PR_Screen = QtWidgets.QLabel(self.centralwidget)
        self.PR_Screen.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.PR_Screen.setObjectName("PR_Screen")
        PictureReceiver.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PictureReceiver)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1286, 24))
        self.menubar.setObjectName("menubar")
        PictureReceiver.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PictureReceiver)
        self.statusbar.setObjectName("statusbar")
        PictureReceiver.setStatusBar(self.statusbar)

        self.retranslateUi(PictureReceiver)
        QtCore.QMetaObject.connectSlotsByName(PictureReceiver)

    def retranslateUi(self, PictureReceiver):
        _translate = QtCore.QCoreApplication.translate
        PictureReceiver.setWindowTitle(_translate("PictureReceiver", "PictureReceiver"))
        self.PR_Screen.setText(_translate("PictureReceiver", "I am a very good picture :D"))
